# Generated by Django 3.2.11 on 2022-01-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
    ]
